### ISSUE TITLE
day of week labels - error (sometimes)

### ISSUE THREAD

**Issue by rrubio** [celsomarques/ionic-datepicker#13]
Hi Guys,

The datepicker looks awesome and i have it running on my app. However, intermittently the dayOfWeek labels give the wrong value (it varies, can be letters or numbers) any tips would be much appreciated.

PS - i don't get any error on console.

![date-picker-day-labels](https://cloud.githubusercontent.com/assets/4221574/13693410/1248fc12-e79f-11e5-8475-5369d91c6e05.png)

**Comment by celsomarques** [comment]
Which version are you using?

Take a look on this:
https://github.com/celsomarques/ionic-datepicker/issues/4

**Comment by celsomarques** [comment]
@rrubio may I close this?
