### ISSUE TITLE
Selected Month and Year is not in the visible area.

### ISSUE THREAD

**Issue by githubramakrishnan** [celsomarques/ionic-datepicker#14]
hi,

If the Month and Year are not in the visible area, how can I bring it up where in the focused Month and Year is always visible.

![ram](https://cloud.githubusercontent.com/assets/11924918/14012465/ed8a150a-f1cb-11e5-86e6-4b8b2dc7b1a4.png)
![ram1](https://cloud.githubusercontent.com/assets/11924918/14012466/ed8bdce6-f1cb-11e5-811f-d4fe2349cc9a.png)

**Comment by celsomarques** [comment]
It's duplicate issue #12
