### ISSUE TITLE
iOS not displaying month and day names

### ISSUE THREAD

**Issue by AaronMorse** [celsomarques/ionic-datepicker#4]
As can be seen in the below screenshots. On the main calendar the Days of the week are showing as 1 1 1 1 1 2 2 instead of M T W T F S S and on the Month picker the month names are also not displaying correctly. This only seems to be an issue on iOS as it works fine in the Chrome.

![img_2282](https://cloud.githubusercontent.com/assets/15925453/11270927/7cefb182-8ecb-11e5-8ed4-29a7a93a9218.jpg)
![img_2283](https://cloud.githubusercontent.com/assets/15925453/11270928/7cf0b8f2-8ecb-11e5-86dc-2add26030d52.jpg)

**Comment by celsomarques** [comment]
Locales and options arguments are not supported on mobile and on Safari (desktop) as can be seen [here](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)

I'll include some json with localised values and I'll change code to use them.

Some help would be great. :)

**Comment by celsomarques** [comment]
I released v1.1.3 to fix this issue. Let me know if it worked, please.

**Comment by AaronMorse** [comment]
Hi Celso, It works. Thank you very much.

**Comment by celsomarques** [comment]
@AaronMorse I fixed another issues about locale.
I included weekdays and months for en-us and pt-br. If you need another one, please open a PR.

I created another tag v1.1.5

Thanks

**Comment by AaronMorse** [comment]
The dates seem to be out of sync now 
![region](https://cloud.githubusercontent.com/assets/15925453/11326165/a700b312-916a-11e5-948b-23444e928783.png)

**Comment by celsomarques** [comment]
I'll take a look

**Comment by celsomarques** [comment]
Could you try again, please?
