### ISSUE TITLE
Time zone Issue  Sri Jayawardenapura

### ISSUE THREAD

**Issue by sampaththeman** [celsomarques/ionic-datepicker#7]
there's a time zone issue in your plugin please fix that soon mate
![uu](https://cloud.githubusercontent.com/assets/9207900/11361985/f0ecedae-92b6-11e5-9dc0-f4b18a880c97.JPG)

**Comment by celsomarques** [comment]
Did you try with latest version (v1.1.6)?

**Comment by sampaththeman** [comment]
Yes . But no luck  :)  look at the calendar dates plz. its Tuesday  24th
 November 2015 but the calendar shows  Tuesday as 23rd November. when i
change my system timezone to US it works fine .

**Comment by AaronMorse** [comment]
Yes this still seems to be an issue in the latest version.

**Comment by celsomarques** [comment]
I made one change to resolve this issue, but opens another one =/
Let me know if it solves this issue, please.

**Comment by sampaththeman** [comment]
It's working fine now thanks :D  Thanks  again
